config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'requirements/new'
  get 'requirements/create'
  get 'tenant/tenant_profile/edit'
  get 'house_owner_profile/edit'
  get 'owner/house_owners/dashboard'
  get 'tenant/tenants/dashboard'
  get 'tenant/tenants/profile'
  get 'home/index'
  get 'home/owner'
  get 'home/tenant'
  get 'home/ghomeshouses'
  get 'home/error'
  get 'payments/bed_confirmation'
  post 'payments/confirmation'
  get 'payments/booking'
  devise_for :tenants, skip: [:sessions]
  devise_for :house_owners, skip: [:sessions]
  devise_for :users, skip: :registrations

   root 'home#index'
  resources :search, only: [:new, :index]
  resources :requirements , only: [:create]
  resources :houses, except: [:index,:destroy]
  resources :visit_schedules, only: [:new,:create,:edit, :show]
  resources :payments
  resources :room_rents, only:[:new,:create, :show]
  resources :reviews, only: [:create]
  resources :deposites, only: [:create,:show]
  namespace :tenant do 
    resources :tenants do
      collection do 
        get :payments
        get :dashboard
        get :myhouse
      end
      resources :tenant_profile, path: :profile
        
    end
  end
  resources :charges 
  get 'charges/booking'
  namespace :owner do
    resources :house_owners do
     collection do 
        get :my_houses
        get :dashboard
        get :my_payments
        get :my_credits
        get :my_notifications
      end
    resources :house_owner_profile
    resources :visit_schedules, only: [:index,:show]
  end
end 

end

app/controllers/houses_controller.rb
  class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
   before_action :auth_owner, except: [:show]
  def auth_owner
    redirect_to  new_house_owner_registration_url unless user_signed_in?
  end
 

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
     @house = House.find(params[:id])
     @visit_schedule=VisitSchedule.new
     @owner_fullname= User.find(@house.house_owner_id).full_name
     @visits = VisitSchedule.group(:house_id).where(house_id: @house.id).count
     @house_owner_image= HouseOwnerProfile.find(@house.house_owner_id).image
     @review = Review.where(house_id: @house.id).all.limit(3)
     
  end

  # GET /houses/new
  def new
    @house = House.new
    @city= City.all
    @house_owner=current_user.id
    @livingroom_amenities = LivingroomAmenitie.all
    @bathroom_amenities = BathroomAmenitie.all
    @bedroom_amenities = BedroomAmenitie.all
    @kitchen_amenities = KitchenAmenitie.all
    @other_amenities = OtherAmenitie.all
  end

  # GET /houses/1/edit
  def edit
    @city= City.all
    @house_owner=current_user.id
    @livingroom_amenities = LivingroomAmenitie.all
    @bathroom_amenities = BathroomAmenitie.all
    @bedroom_amenities = BedroomAmenitie.all
    @kitchen_amenities = KitchenAmenitie.all
    @other_amenities = OtherAmenitie.all
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)
    @house_owner=current_user.id
    
    @city= City.all
     @livingroom_amenities = LivingroomAmenitie.all
    @bathroom_amenities = BathroomAmenitie.all
    @bedroom_amenities = BedroomAmenitie.all
    @kitchen_amenities = KitchenAmenitie.all
    @other_amenities = OtherAmenitie.all
    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def book_house
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:name,:house_type,:house_for,:no_of_rooms,:no_of_beds,:rent_per_room,
                    :rent_per_bed,:food_preference, :city, :location,:latitude, :longitude, :house_owner_id,:distance_from_station, :livingroom_amenities  => [],
                    :bedroom_amenities  => [],:bathroom_amenities  => [],
                    :kitchen_amenities  => [],:other_amenities  => [],:house_image => []
                    )
    end
  
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<div class="house-form">
  <%= form_for @house, html: {multipart: :true} do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h4>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-sm-6">
      <%= f.hidden_field :house_owner_id, value:@house_owner %>
      <div>
        <label>Name</label>
        <%= f.text_field :name, placeholder:"name",required:'true'%>
      </div>
      <div>
        <label>House Type</label> 
        <div class="select-option">
          <i class="ti-angle-down"></i>
          <%=f.select :house_type, options_for_select([['Apartment'],['bungalow'],['1BHK'],['2BHK'],['3BHK'],['duplex']])%>
        </div>
      </div>
      <div>
        <label>City</label>
        <div class="select-option">
          <i class="ti-angle-down"></i>
          <%=f.select :city, options_for_select(@city.all.collect {|c| [ c.name, c.name ] })%>
        </div>
      </div>
      <div>
        <label>Enter location and select house using map</label>
        <%= f.text_field :location, placeholder:"location"%>
        <div><%= f.text_field :latitude , placeholder:"latitude",readonly:"readonly"%></div>
        <div><%= f.text_field :longitude , placeholder:"longitude",readonly:"readonly"%></div>      
        <div>
          Your house Lattitude: <span id="latspan">22.74</span>
          Your house Longitude: <span id="lngspan">22.74</span>
          click on map select your house
        </div>
      </div>
      <div id="mapdiv" style="width: 100%;height: 250px;">
        <div id="crosshair"></div>
      </div>
      <div>
        <label>House for</label>
        <div class="select-option">
          <i class="ti-angle-down"></i>
          <%=f.select :house_for, options_for_select([['Boys'],['Girls']])%>
        </div>
      </div>  
      <div>
        <label>No of rooms</label>
        <%= f.number_field :no_of_rooms, class: 'text_field', step: 1, required:'true'  %>
      </div>
      <div>
        <label>no_of_beds</label>
        <%= f.number_field :no_of_beds, class: 'text_field', step: 1, required:'true'  %>
      </div>
        
    </div>
    <div class="col-sm-6"> 
      <div>
        <label>rent_per_bed</label>
        <%= f.number_field :rent_per_bed, class: 'text_field', required:'true' %>
      </div>
      <div>
        <label>rent_per_room</label>
        <%= f.number_field :rent_per_room, placeholder:"Rent per Room", required:'true' %>
      </div>
      <div>
        <label>food_preference</label>
        <div class="select-option">
          <i class="ti-angle-down"></i>
          <%=f.select :food_preference, options_for_select([['None'],['Veg only'],['All']])%>
        </div>
      </div>     
      <div>
        <label>livingroom_amenities</label>
        <%= f.select :livingroom_amenities, @livingroom_amenities.all.collect {|p| [ p.name, p.name ] }, {:include_hidden => false},{placeholder: 'Type or select a amenitie', id: 'livingroom_amenitie', multiple: 'multiple'} %>
      </div>
      <div>
        <label>bedroom_amenities</label>
        <%= f.select :bedroom_amenities, @bedroom_amenities.all.collect {|p| [ p.name, p.name ] }, {:include_hidden => false},{placeholder: 'Type or select a amenitie', id: 'bedroom_amenitie', multiple: 'multiple'} %>
      </div>
      <div>
        <label>bathroom_amenities</label>
         <%= f.select :bathroom_amenities, @bathroom_amenities.all.collect {|p| [ p.name, p.name ] }, {:include_hidden => false},{placeholder: 'Type or select a amenitie', id: 'bathroom_amenitie', multiple: 'multiple'} %>
      </div>
      <div>
        <label>kitchen_amenities</label>
         <%= f.select :kitchen_amenities, @kitchen_amenities.all.collect {|p| [ p.name, p.name ] }, {:include_hidden => false},{placeholder: 'Type or select a amenitie', id: 'kitchen_amenitie', multiple: 'multiple'} %>
      </div>
      <div>
        <label>other_amenities</label>
         <%= f.select :other_amenities, @other_amenities.all.collect {|p| [ p.name, p.name ] }, {:include_hidden => false},{placeholder: 'Type or select a amenitie', id: 'other_amenitie', multiple: 'multiple'} %>
      </div>
      <div>
        <label>house_image</label>
        <%= f.file_field :house_image, multiple: true %>
      </div>
      <div>
        <label>distance_from_station</label>
        <%= f.text_field :distance_from_station%>
      </div>
    </div>
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.submit %>
    </div>
    
  <% end %>

</div>
<%= render 'shared/amenities', object: 'livingroom_amenities' %>
<%= render 'shared/amenities', object: 'bedroom_amenities' %>
<%= render 'shared/amenities', object: 'bathroom_amenities' %>
<%= render 'shared/amenities', object: 'kitchen_amenities' %>
<%= render 'shared/amenities', object: 'other_amenities' %>
<script type="text/javascript">
window.onload = function () { mapa() };
  //$("#house_location").geocomplete();
  
  $('#house_livingroom_amenities').selectize({
    delimiter: ',',
    persist: false,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
  });
  $("#house_location").geocomplete()
// lat lang using manual entry
  // $("#house_location").geocomplete().bind("geocode:result", function(event, result){
  //   var lat = result.geometry.location.lat();
  //   var lng = result.geometry.location.lng();
  //   $('#house_latitude').val(lat);
  //   $('#house_longitude').val(lng);
  //   console.log(lat)
  //   console.log(lng)
  //   });

  // Lat lng using map////

  var map; 
  function mapa() { 
    var opts = {
      'center': new google.maps.LatLng(22.79, 76.35),
      'zoom':8, 
      'mapTypeId': google.maps.MapTypeId.ROADMAP 
    } 
    map = new google.maps.Map(document.getElementById('mapdiv'),
     opts
     ); 
    google.maps.event.addListener(map,'click',function(event) { 
      document.getElementById('house_latitude').value = event.latLng.lat() 
      document.getElementById('house_longitude').value = event.latLng.lng() 
      var clickLat = event.latLng.lat();
      var clickLon = event.latLng.lng();
      marker = new google.maps.Marker({position: event.latLng, map: map});
   }) 

    google.maps.event.addListener(map,'mousemove',function(event) { 
     document.getElementById('latspan').innerHTML = event.latLng.lat()
     document.getElementById('lngspan').innerHTML = event.latLng.lng()
   }); 
     m
  }
// // // //
</script>

app/views/houses/_house_review.html.erb
<div class="container-fluid" id="house-reviews" style="margin:10px;">
	<h4 class="uppercase">Reviews</h4>
	<div class="well">
		<ul>
			<li>
			<% @review.each do |review|%>
				<div class="row">
					
					<div class="col-xs-3">

						<% tenant = TenantProfile.where(tenant_id: review.tenant_id).first %>
						<% @reviewer = User.find(tenant.tenant_id) %>
						<%= image_tag tenant.image.url(:thumb)%>
					</div>
					<div class="col-xs-9">
						<h5><%= @reviewer.full_name %></h5>
						<p><%= review.message %></p>
					</div>
					
				</div>
				<hr>
				<% end %>
			</li>
		</ul>
	</div>
</div>

app/views/houses/_house_rules.html.erb
<div style="padding:5px;">
	<div>
	<h6 class="uppercase">House ruls</h6>
	<ul>
		<li class="upeercase lead">Seven Commandments</li>
		<li>1. You shall take care of the home as your own</li>
		<li>2. You shall look after you roommates like a family</li>
		<li>3. You shall be good to neighbours & not wake them up midnight</li>
		<li>4. You shall not host guests of opposite gender beyond 7 PM</li>
		<li>5. You shall invite us on your birthday</li>
		<li>6. You shall party hard but clean up afterwards</li>
		<li>7. You shall introduce your roommates to The Big Bang Theory</li>
	</ul>
	</div>
</div>

app/views/houses/edit.html.erb
<section class="pt40">
<div class="container-fluid">
	<h1>Editing House</h1>

	<%= render 'form' %>
	<div class="col-sm-4 col-sm-offset-4">
		<%= link_to 'Show', @house %> |
		<%= link_to 'Back', houses_path %>
	</div>
	
</div>	
</section>

app/views/houses/index.html.erb
<section>
  <p id="notice"><%= notice %></p>

<h1>Listing Houses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

</section>

app/views/houses/new.html.erb
<section>
	<div class="container-fluid">
		<h1>New House</h1>

		<%= render 'form' %>

		<%= link_to 'Back', houses_path %>
	</div>
</section>

app/views/houses/show.html.erb
<section class="pb0">
	<div class="container">
		<p class="flash-notice" style="color:red"><%= alert %></p>
		<div class="house-details">
			<div class="row">
				<div class="col-sm-8">
					<div class="row">
						<div class="col-sm-12 module widget-handle hidden-xs" style="min-height: 41px; border:1px;">
							<nav>
								<ul class="nav nav-offer menu">
									<li>
										<a class="nav-link" href="#Overview" class="overview-btn">Overview</a>
									</li>	
									<li>
										<a class="nav-link inner-link" href="#house-amenities" class="amenities-btn">Amenities</a>
									</li>
									<li>
										<a class="nav-link inner-link" href="#house-on-map" >Map</a>
									</li>
									<li>
										<a class="nav-link inner-link" href="#house-conditions" >Conditions</a>
									</li>
									<li>
										<a class="nav-link inner-link" href="#house-reviews" >Reviews</a>
									</li>
								</ul>
							</nav>
						</div>	
					</div>	<!-- end of row -->		
					<div id="myCarousel" class="carousel slide" data-ride="carousel">
						<!-- Indicators -->
						<% i= 0%> 
						<% count= @house.house_image.count %>
						<ol class="carousel-indicators">
							<% for i in 0..count-1 do%>
							<li data-target="#myCarousel" data-slide-to= <%= i %> >
							</li>
							<% i = i+1%>
							<% end %>
						</ol>

						<!-- Wrapper for slides -->
						<div class="carousel-inner" role="listbox">
							<% @house.house_image.each_with_index do |image, index|%>
							<div style="background: url(<%=image.url%>) center center; background-size:cover;" class="slider-size image-responsive item <%='active' if index == 0%>" data-slide-to="<%= index %>">
							</div>
							<%end%>
						</div>

						<!-- Left and right controls -->
						<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
							<span class="sr-only">Previous</span>
						</a>
						<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
							<span class="sr-only">Next</span>
						</a>
					</div>
				</div>
				<% if current_user.class == Tenant || user_signed_in? == false %>
				<div class="col-sm-4 house-details-right">
					<div class="house-right-tabs">
						<!-- Nav tabs -->
						<ul class="nav nav-tabs" role="tablist">
							<li role="presentation" class="active"><a href="#schedule-house" aria-controls="schedule-house" role="tab" data-toggle="tab">Schedule a visit</a></li>
							<li role="presentation"><a href="#book-house" aria-controls="book-house" role="tab" data-toggle="tab">Book Now</a></li>
						</ul>

						<!-- Tab panes -->
						<div class="tab-content">
							<div role="tabpanel" class="tab-pane active" id="schedule-house">
								<%= render 'visit_schedules/form'%>
							</div>
							<div role="tabpanel" class="tab-pane" id="book-house">
								<div>
									<h5 style="margin: 10px;">To Book, you need to pay a token amount and the remaining before move-in. </h5>
									<div align="center"><%= link_to 'book', payments_bed_confirmation_path(house_id: @house.id), class:'btn'%></div>
									<div>
										<div class="col-sm-3 visit-count" align="center">
											<p class="uppercase"><span><%=@visits[@house.id]%></span> Visits</p>
										</div>
										<div class="col-sm-9">
											<span><strong>Already Scheduled</strong></span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			</div>   <!-- end of row -->
		</div>
	</div>	
</section>
<section class="pt0">
	<div class="container">
		<div class="row">
			<div class="col-sm-8">
				<div class=row>
					<div class="subpanel">
						<ul class="house-overview">
							<li class="house-overview-item">
								<div class="house-overview-title">Type</div> 
								<div class="house-overview-body "><%= @house.house_type%></div>
							</li>
							<li class="house-overview-item">
								<div class="house-overview-title">Only For</div> 
								<div class="house-overview-body "><%= @house.house_for%></div>
							</li>
							<li class="house-overview-item">
								<div class="house-overview-title">Rooms</div> 
								<div class="house-overview-body "><%= @house.no_of_rooms%></div>
							</li>
							<li class="house-overview-item">
								<div class="house-overview-title">Bed</div> 
								<div class="house-overview-body "><%= @house.no_of_beds%></div>
							</li>
						</ul>			
					</div>
				</div>
				<div class="house-rent-detail row mt8">
					<div class="col-xs-6">
						<h5>Rent</h5>
						<h5><%=@house.rent_per_bed%></h5>
					</div>
					<div class="col-xs-6">
						<h5>Security Deposit</h5>
						<h5><%=2*@house.rent_per_bed%></h5>
					</div>	
				</div>

				<div class="row mt8" id="house-amenities">
					<div  class="mt8">
						<div class="amenities-list">
							<h4 class="uppercase">Home Amenities</h4>
							<div class="col-sm-6">
								<h5><strong>Living Room</strong></h5>
								<ul>
									<% @house.livingroom_amenities.each do |amenities| %>
									<li><%= amenities %></li>
									<% end %>
								</ul>
							</div>
							<div class="col-sm-6">
								<h5><strong>Kitchen</strong></h5>
								<ul>
									<% @house.kitchen_amenities.each do |amenities| %>
									<li><%= amenities %></li>
									<% end %>
								</ul>
							</div>
							<div class="col-sm-6">
								<h5><strong>bedroom</strong></h5>
								<ul>
									<% @house.bedroom_amenities.each do |amenities| %>
									<li><%= amenities %></li>
									<% end %>
								</ul>
							</div>
							<div class="col-sm-6">
								<h5><strong>Bathroom</strong></h5>
								<ul>
									<% @house.bathroom_amenities.each do |amenities| %>
									<li><%= amenities %></li>
									<% end %>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="row mt8">
					<div class="house-detail-table">
						<div>
							<h4 class="uppercase">Property Summary</h4>
						</div>	
						<table class="house-desc table">
							<tr>
								<td class="att">GoogleHomes Home Id:  </td><td class="att-title"><%=@house.city%></td>
							</tr>
							<tr>
								<td class="att">Address:  </td><td class="att-title"><%=@house.location%></td>
							</tr>
							<tr>
								<td class="att">City:  </td><td class="att-title"><%=@house.city%></td>
							</tr>
							<tr>
								<td class="att">House Type:  </td><td class="att-title"><%=@house.house_type%></td>
							</tr>							
							<tr>
								<td class="att">For:  </td><td class="att-title"><%=@house.house_for%></td>
							</tr>
							<tr>
								<td class="att">Food Preference:  </td><td class="att-title"><%=@house.food_preference%></td>
							</tr>
							<tr>
								<td class="att">Distance from station:  </td><td class="att-title"><%=@house.distance_from_station%></td>
							</tr>
						</table>
					</div>
				</div>
				<div class="row mt8">
					<div id="house-on-map" style="margin:10px;height: 300px;">
						
					</div>
				</div>
			</div>
			<div class="col-sm-4 ">
				<div class=" row hw-detail">
					<h4 class="uppercase">House owner</h4>
					<div align="center">
						<%= image_tag @house_owner_image.url%>
						<div class="hwname" >
							<h4><%= @owner_fullname%></h4>
						</div>
					</div>	
				</div>
				<div class="customer-story row">
					<h4 class="uppercase">Customer Stories</h4>
				</div>
			</div>
		</div>				
	</div>
</section>
<div class="container-fluid">
	<div class="house-rule"> 
	<%= render 'house_rules' %>
</div>
</div>
<section class="pt0">
<%= render 'house_review'%>
</section>
<section class="pt0">
	<div class="similar-house container-fluid" >
		<h5 class="uppercase">Similar house</h5>
		<div class="col-sm-4" style="border: 1px #ccc solid; margin:5px;">
			<div style="margin:5px;">
				<%= image_tag 'arch6.jpg', class: 'image-responsive'%>
				<div class="similar-house-price">Rs. <%= @house.rent_per_bed%></div>
			</div>
			<div>
				<%= @house.location %>
			</div>
		</div>
	</div>
</section>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'house-on-map'}}, function(){
		markers = handler.addMarkers([
		{
			"lat": <%=@house.latitude%>,
			"lng": <%=@house.longitude%>
		}
		]);
		handler.bounds.extendWith(markers);
		handler.map.centerOn(markers[0]);
		handler.getMap().setZoom(15);
	});

</script>
<!-- <div class="col-sm-4 owner-detail" >
				<div class="col-sm-4 owner-image">
					<%#=image_tag "avatar.png"%>
				</div>
				<div  class="col-sm-8 owner-name">
					<span>House Owner</span>
					<h5><strong><%#= @owner_fullname%></strong></h5>
				</div>
			</div> -->	