config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'requirements/new'
  get 'requirements/create'
  get 'tenant/tenant_profile/edit'
  get 'house_owner_profile/edit'
  get 'owner/house_owners/dashboard'
  get 'tenant/tenants/dashboard'
  get 'tenant/tenants/profile'
  get 'home/index'
  get 'home/owner'
  get 'home/tenant'
  get 'home/ghomeshouses'
  get 'home/error'
  get 'payments/bed_confirmation'
  post 'payments/confirmation'
  get 'payments/booking'
  devise_for :tenants, skip: [:sessions]
  devise_for :house_owners, skip: [:sessions]
  devise_for :users, skip: :registrations

   root 'home#index'
  resources :search, only: [:new, :index]
  resources :requirements , only: [:create]
  resources :houses, except: [:index,:destroy]
  resources :visit_schedules, only: [:new,:create,:edit, :show]
  resources :payments
  resources :room_rents, only:[:new,:create, :show]
  resources :reviews, only: [:create]
  resources :deposites, only: [:create,:show]
  namespace :tenant do 
    resources :tenants do
      collection do 
        get :payments
        get :dashboard
        get :myhouse
      end
      resources :tenant_profile, path: :profile
        
    end
  end
  resources :charges 
  get 'charges/booking'
  namespace :owner do
    resources :house_owners do
     collection do 
        get :my_houses
        get :dashboard
        get :my_payments
        get :my_credits
        get :my_notifications
      end
    resources :house_owner_profile
    resources :visit_schedules, only: [:index,:show]
  end
end 

end

app/models/booked_house.rb
class BookedHouse < ActiveRecord::Base
	belongs_to :house
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :tenant
	belongs_to :house
end

app/models/city.rb
class City < ActiveRecord::Base
	
end

app/models/deposite_rent.rb
class DepositeRent < ActiveRecord::Base
	belongs_to :house
	belongs_to :tenant
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :house_owner
	has_many :bookings
	has_many :deposite_rents
	has_many :room_rents
	has_many :tenants 
	has_many :visit_schedules
	has_many :booked_houses

	validates :house_image, :city, :location, :latitude, :longitude, presence: true
	
	mount_uploaders :house_image, ImageUploader
	
	acts_as_mappable :default_units => :kms,:lat_column_name => :latitude, :lng_column_name => :longitude

end

app/models/house_owner.rb
class HouseOwner < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  	has_one :house_owner_profile
  	has_many :houses
	has_many :visit_schedules
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/other_amenitie.rb
class OtherAmenitie < ActiveRecord::Base
end

app/models/owner_payment.rb
class OwnerPayment < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
	validates :name, :phone, :email, :room_for, :city, :location, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base 
end

app/models/room_rent.rb
class RoomRent < ActiveRecord::Base
	belongs_to :house
	belongs_to :tenant
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  has_one :tenant_profile
  has_many :bookings
  has_many :room_rents
  has_many :deposite_rents 
  belongs_to :house
  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/tenant_profile.rb
class TenantProfile < ActiveRecord::Base
	belongs_to :tenant
	def full_permamnent_address
		l = ''
		l << p_address if p_address && !p_address.blank?
    l << ' '
		l << p_city if p_city && !p_city.blank?
    l << ' '
		l << p_state if p_state && !p_state.blank?
  	end

  	#validates :DOB, :sex, :p_address, :p_city, :p_state, presence: true
  	mount_uploader :image, ImageUploader
  	mount_uploader :address_proof, ImageUploader
  	mount_uploader :identity_proof, ImageUploader
  	mount_uploader :cheque, ImageUploader
  	mount_uploader :employment_proof, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :first_name, :last_name, :contact_number, presence: true 
  # #mount_uploader :avatar, LogoUploader

  after_create :send_signup_mail
  
    def send_signup_mail
      UserMailer.signup_mail(self).deliver
    end


  # def should_be_house_owner_user?
  #   type == "HouseOwner"
  # end

  # def should_be_tenant_user?
  #   type == "Tenant"
  # end
 end

app/models/visit_schedule.rb
class VisitSchedule < ActiveRecord::Base
	belongs_to :house
	belongs_to :house_owner
	validates :name, :email, :phone, :date, :time, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	before_action :auth_tenant

	def auth_tenant
	    redirect_to  new_tenant_registration_url unless user_signed_in?
	end

	def new
  	end
  		

  	def create
  		
  	end

	def bed_confirmation
		house = params[:house_id]
		@house = House.find(house)
		@move_in_date = params[:date]
		@token_amount = params[:token].to_f
		@rent_amount = params[:rent].to_f
		@month = params[:month]
		@bed_room = params[:bed_room]
		@tenant = current_user
			
		if BookedHouse.where(tenant_id: @tenant).first != nil
			redirect_to :back, alert: 'You have already booked a house'
		end
		
	end

	def confirmation
		house = params[:house_id]
		@house = House.find(house)
		@move_in_date = params[:date]
		@token_amount = params[:token].to_f
		@rent_amount = params[:rent].to_f
		@month = params[:month]
		@bed_room = params[:bed_room]
		@tenant = current_user	
	end

	def show
		@booking = Booking.find(params[:id])
		@house =  House.find(@booking.house_id)		
		@tenant = current_user
	end

	def booking
		@user = current_user
		UserMailer.booking_email(@user).deliver
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/payments/bed_confirmation.html.erb
<section style="background: #f5f5f5 none repeat scroll 0 0 !important;" class="pt40">
	<div class="col-sm-6 col-sm-offset-3" style="background: #ccc;"> 
		<div class="payment-widget-card">
			<div class="payment-gender-choose">
				<strong>This house is available for <%= @house.house_for %>.</strong>
			</div>
		</div>
		<div class="payment-widget-content">
			<div id="sharing_option"class="animated fadeIn booking-option option-bed">
				<h6 class="text-center">Click on bed to select</h6>
				<div class="row text-center">
					<ul class="select-bed-list">
						<%i=@house.no_of_beds%>
						<% j=1 %>
						<% for room in 1..@house.no_of_rooms %>
						<div class="row">
							<li>
								<div class="col-sm-4">
									<h5>Bedroom <%= room%></h5>
								</div>
							</li>
							<li>
								<div class="col-sm-8 choose-bed-widget">
									<% for bed in 1..2 %>
									<input type="radio" name="bed_id" id="bed<%= @house.id%><%= room%><%= j%>" class="chosen-bed" value="<%= @house.rent_per_bed %>">
									<label for="bed<%= @house.id%><%= room%><%= j%>"><i class="ti-layout-cta-left"><br></i><%= @house.rent_per_bed%></label>
									<%j+=1%>
									<% if j==i then%>
									<%break %>
									<%end %>
									<%end%>
								</div>
							</li>
						</div>
						<%end%>
					</ul>					
				</div>
			</div>
			<div id="sharing_option"class="animated fadeIn booking-option option-room">
				<h6 class="text-center">Click on room to select</h6>
				<div class="row text-center">
					<ul class="select-bed-list">
						<% r=0 %>
						<% for room in 1..@house.no_of_rooms %>
						<div class="row">
							<li>
								<div class="col-sm-4">
									<h5>Room <%= room%></h5>
								</div>
							</li>
							<li>
								<div class="col-sm-8 choose-bed-widget">
									
									<input type="radio" name="bed_id" id="room<%= @house.id%><%= r%>" class="chosen-bed" value="<%= @house.rent_per_room %>">
									<label for="room<%= @house.id%><%= r%>"><i class="ti-layout-cta-left"><br></i><%= @house.rent_per_room%></label>
									<%r+=1%>
								</div>
							</li>
						</div>
						<%end%>
					</ul>					
				</div>
			</div>
			<div class="rent-option">
				<h6 class="text-center">Choose your booking type</h6>
				<div class="roomtype text-center">

					<label class="bed-type-btn">
						<input type="radio" value="bed" style="margin-right: 6px;" name="bed_type" id="shared" checked="checked"><b>Shared Room</b>
					</label>
					<label class="bed-type-btn">
						<input type="radio" value="room" style="margin-right: 6px;" name="bed_type" id="private"><b>Private Room</b>
					</label>
					<label style="border:0; padding-right:20px;" class="bed-type-btn">
						<input type="radio" value="house" style="margin-right: 6px;" name="bed_type" id="house"><b>House</b>
					</label>
				</div>
			</div>	
		</div>
<!-- hidden fields for room and bed -->
	<!-- <div class="form-group hidden">
    <%#= hidden_field_tag :bed, nil, id: 'selected-bed', value: params[:bed] %>
  </div>
  <div class="form-group hidden">
    <%#= hidden_field_tag :room, nil, id: 'selected-room', value: params[:room] %>
  </div> --> 
<!-- end of hidden fields -->
		<div id="movein-popup" class="movein-popup-payment">
			<div class="movein-popup-widget">
				<div class="date-popup-header">
					<div>Set your move in date</div>
					<div style="" id="available-date" class="date-available">You can only move-in after 48 hours from bed available date.</div>
					<div class="movein-info" style="display: none;">Please choose your move in date</div>
				</div>
				<span class="error-date"></span>
				<div class=" row move-date-widget">
					<div class="col-xs-2">
						<span class="pe-7s-date"></span>
					</div>
					<div class="col-xs-10">
						<input type="text" readonly="" required="true" placeholder="select move in date" id="datepicker-disable-past" name="move_in_date">
						
					</div>
				</div>
				<div class="movein-footer">
					<a id="choose-move-date-close" href="" class="btn"> Cancel</a>
					<a id="movein-ok-btn" class="btn"> Set move in date</a>
				</div>
			</div>
		</div>
		<div class="row chosen-move-in-date">
			<h6>Your chosen move in date</h6>
			<h4 class= 'date-text' style="color: #47B59C;"></h4>
			
			<div class="col-sm-8">
				<div class="col-sm-6">
					<a id="choose-move-date-close" href="" class="btn"> Cancel</a>
				</div>
				<%= form_tag payments_confirmation_path do %>
				<%= hidden_field_tag :date, nil, id: 'move-in-date', value: params[:date] %>
				<%= hidden_field_tag :house_id, nil, id: 'ghomes-house_id', value: params[:house_id] %>
				<%= hidden_field_tag :token, nil, id: 'token-amount', value: params[:token] %>
				<%= hidden_field_tag :rent, nil, id: 'rent-amount', value: params[:rent] %>
				<%= hidden_field_tag :month, nil, id: 'rent-month', value: params[:month] %>
				<%= hidden_field_tag :bed_room, nil, id: 'bed-room', value: params[:bed_room] %>
				<div class="col-sm-6">
					<input type="submit" value="Go for payment" class="bed-submit"/>
				</div>
				<% end %>
			</div>
		</div>
		<div>
		</section>

		<script type="text/javascript">
			var full_rent;
			$('#datepicker-disable-past').datepicker({
			  dateFormat: "dd-mm-yy",
			  minDate: 2 });
			$('#movein-popup').hide();
			$('.chosen-move-in-date').hide();
			$('.option-room').hide();

			$(".choose-bed-widget input[type=radio]").click(function () {
				$('.payment-widget-content').hide("slide", {direction: "down" }, 500);
				$('.rent-option').hide("slide", {direction: "down" }, 500);
				$('.chosen-move-in-date').hide("slide", {direction: "down" }, 500);
				$('#movein-popup').show("slide", {direction: "up" }, 500 );
				});
				$('.choose-bed-widget input[type=radio]').on('change', function() {
				 $(this).prop("checked", true);
					full_rent = $(this).val();
					var id= $(this).attr('id');
					$('#bed-room').val(id);
					console.log(id)
					
					// $('#token-amount').val($(this).val()/2);
					// console.log($(this).val()/2)
				
				
				
				event.preventDefault();
			});
				$('#shared').click(function(event){
					$('.option-bed').show();
					$('.option-room').hide();
					
				});

				$('#private').click(function(event){
					$('.option-bed').hide();
					$('.option-room').show();
				});

			$('#movein-ok-btn').click(function(event){
				var date = $('#datepicker-disable-past').val();
				var dateArray = date.split('-');
				var dateDay = dateArray[0];
				if(date == ""){
					$('.error-date').html('Please select date')
					
				}
				else{
					
					
					$('.chosen-move-in-date').show("slide", {direction: "down" }, 500 );
					$('.date-text').html(date);
					$('#move-in-date').val(date);
					$('#ghomes-house_id').val(<% @house.id %>);
					$('#rent-month').val(dateArray[1]);
					$('#movein-popup').hide();
					$('.rent-option').show("slide", {direction: "down" }, 500);
					$('.payment-widget-content').show("slide", {direction: "down" }, 500 );

				}
					$('#rent-amount').val(full_rent)
					if(dateDay>15){
						$('#token-amount').val(full_rent/2)
					}
					else{
						$('#token-amount').val(full_rent)
					}
					// $('#token-amount').val($(this).val()/2);
					// console.log($(this).val()/2)
					
				event.preventDefault();
			});


		</script>

app/views/payments/confirmation.html.erb
<section>
	<div class="col-sm-6 col-sm-offset-3 confirmation-widget">
		<div class="row">
			<div class="token-widget">
				<div>
					<h5>Advance token Money</h5>
				</div>

				<div>
					<h3 style="color:#E73400">Total
						<span style="text-align: right">₹ <%= @token_amount %></span></h3>
						<h5>first month Room/House Rent</h5>
					</div>
					<%= form_tag charges_path do %>
					<ul class="form-wrapper add-merchant clearfix">
						<li>
							
							<%= hidden_field_tag 'house_id',nil, value: params[:house_id] %>
							<%= hidden_field_tag 'rent',nil, value: params[:rent].to_f%>
							<%= hidden_field_tag 'month',nil, value: params[:month] %>
							<%= hidden_field_tag 'tenant',nil, value: current_user.id%>
							<%= hidden_field_tag 'bed_room',nil, value: params[:bed_room] %>
							<%= hidden_field_tag 'token', nil, value: params[:token] %>
							<input type="hidden" value="<%= Time.now %>" name="booking_date">
							<%= hidden_field_tag 'move_in_date',nil, value: params[:date] %>
						</li>
					</ul>
					<div class="gender-agree">
						<input type="checkbox" title="Please accept T&amp;C" required="" value="" id="terms_check" name="">
						<label style="font-weight:normal" for="tenant"> &nbsp;
							I agree to <a target="_blank" style="color:#4bb39b; text-decoration:underline" href="/welcome/tenant_terms">Terms and Conditions</a>
						</label>
						<p class="error terms-error animated shake"></p>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<input type="submit" value="Pay <%= @token_amount %>" />
						</div>
						<div class="col-sm-6">
							<%= link_to 'Cancle', :back, class:'btn btn-lg btn-cancle'%>
						</div>
					</div>
					<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
					  data-description="Pay Token money/first month rent" data-label = 'Pay Now'
					  data-amount="<% params[:rent].to_i%>"
					  data-locale="auto">
				  </script>
				<% end %>
			</div>

		</div>
		<div class="row">
			<div class="panel-group details-widget" id="accordion">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#person-detail"><i class="glyphicon glyphicon-minus"></i>Person-details</a>
						</h4>
					</div>
					<div id="person-detail" class="panel-collapse collapse in">
						<div class="panel-body">
							<table class="table detail-table">
								<tr>
									<td>Name</td>
									<td><%= @tenant.full_name %></td>
								</tr>
								<tr>
									<td>Email</td>
									<td><%= @tenant.email %></td>
								</tr>
								<tr>
									<td>Mobile</td>
									<td><%= @tenant.contact_number %></td>
								</tr>
								<tr>
									<td>Move in Date</td>
									<td style="color:#47B475;"><%= @move_in_date %></td>
								</tr>
							</table>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#terms"><i class="glyphicon glyphicon-plus"></i>Terms</a>
						</h4>

					</div>
					<div id="terms" class="panel-collapse collapse">
						<div class="panel-body">Contents panel 2</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#house-detail"><i class="glyphicon glyphicon-plus"></i>House-details</a>
						</h4>
					</div>
					<div id="house-detail" class="panel-collapse collapse">
						<div class="panel-body">
							<div class="row">
								<div class="col-sm-8 col-sm-offset-2">
									<%= image_tag @house.house_image.first.url, class:'img-responsive'%>
								</div>	
							</div>
							<div class="row">
								<h5  style="color:#47B475;"><%= @house.name %></h5>
								<h6><%= @house.location %></h6>									
								<table  class="table detail-table">

									<tr>
										<td>House Type</td>
										<td><%= @house.house_type %></td>
									</tr>
									<tr> 
										<td>House Id</td>
										<td>GH <%= @house.id %></td>
									</tr>
									<tr>
										<td>House for</td>
										<td><%= @house.house_for %></td>
									</tr>
									<tr>
										<td>Food preference</td>
										<td><%= @house.food_preference %></td>
									</tr>
								</table>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#rent-cover"><i class="glyphicon glyphicon-plus"></i>What your rent covers</a>
						</h4>

					</div>
					<div id="rent-cover" class="panel-collapse collapse">
						<div class="panel-body">
							<div class="row">
								<ul>
									<li>Home and furnishing charges</li>
									<li>Building maintenance charges wherever applicable</li>
									<li>Free service visit charges upto INR 500/ month</li>
								</ul>
							</div>
							<div class="row">
								<h5>What your rent does not cover</h5>
								<ul>
									<li>Monthly Water & Electricity Charges</li>
									<li>Refilling Cooking Gas</li>
									<li>DTH and Internet monthly charges</li>
									<li>Basically, any recurring charges including food</li>
									<li>Minor structural repairs, cleaning & more <a data-toggle="modal" data-target="#myModal" style="cursor: pointer;">(See details)</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h5 class="modal-title uppercase" id="myModalLabel">Day to day repairs to be done by Tenant</h5>
			</div>
			<div class="modal-body">
				<ul>
					<li>1. Changing of tap washers and taps.</li>
					<li>2. Drain cleaning.</li>
					<li>3. Water closet repairs.</li>
					<li>4. Wash Basin repairs. </li>
					<li>5. Bath tub repairs. </li>
					<li>6. Geyser repairs. </li>
					<li>7. Circuit breaker repairs. </li>
					<li>8. Switches and socket repairs, Replacement of bulbs.</li>
					<li>9. Repairs and replacement of electrical equipment except major internal and external wiring change.</li>
					<li>10. Kitchen fixtures repairs. </li>
					<li>11. Replacement of knobs and locks of doors, cupboard windows etc.</li>
					<li>12. Replacement of flynets. </li>
					<li>13. Replacement of glass panels in windows, doors etc. </li>
					<li>14. Maintenance of gardens and open spaces let out to the tenant.</li>
					<li>15. Servicing & Maintenance of appliance & furniture.</li>
					<h5><span style="color:#648900"><strong>Maintenance timings:</strong></span> <strong>9 AM - 6PM</strong> on <strong>Mon-Sat</strong> except holidays subject to prior intimation & tenant availability </h5>
				</ul>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	var selectIds = $('#person-detail,#terms,#rent-cover,#house-detail');
	$(function ($) {
		selectIds.on('show.bs.collapse hidden.bs.collapse', function () {
			$(this).prev().find('.glyphicon').toggleClass('glyphicon-plus glyphicon-minus');
		})
	});
	$('.checkbox-option').on("click",function() {
		$(this).toggleClass('checked');
		var checkbox = $(this).find('input');
		if (checkbox.prop('checked') === false) {
			checkbox.prop('checked', true);
		} else {
			checkbox.prop('checked', false);
		}
	});
	$('.stripe-button-el').hide();
</script>

app/views/payments/show.html.erb
<section class="pt20">
		<div class="container">
			<div class="row">
				<div class="box">
					<h4><%= current_user.first_name %> Your booking confirmed.</h4>
					<h5>House: <span><%= @house.name %></span></h5>
					<h5>House Location: <span><%= @house.location %></span></h5>
					<h5>Token money: <span><%= @booking.token_money %></span></h5>
					<h5>Booking in date : <span><%= @booking.booking_date %></span></h5>
					<h5>Move in date : <span><%= @booking.move_in_date %></span></h5>
				</div>
			</div>
			<%= link_to "Go to dashboard", dashboard_tenant_tenants_path%>
		</div>
	</section>