config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'requirements/new'
  get 'requirements/create'
  get 'tenant/tenant_profile/edit'
  get 'house_owner_profile/edit'
  get 'owner/house_owners/dashboard'
  get 'tenant/tenants/dashboard'
  get 'tenant/tenants/profile'
  get 'home/index'
  get 'home/owner'
  get 'home/tenant'
  get 'home/ghomeshouses'
  get 'home/error'
  get 'payments/bed_confirmation'
  post 'payments/confirmation'
  get 'payments/booking'
  devise_for :tenants, skip: [:sessions]
  devise_for :house_owners, skip: [:sessions]
  devise_for :users, skip: :registrations

   root 'home#index'
  resources :search, only: [:new, :index]
  resources :requirements , only: [:create]
  resources :houses, except: [:index,:destroy]
  resources :visit_schedules, only: [:new,:create,:edit, :show]
  resources :payments
  resources :room_rents, only:[:new,:create, :show]
  resources :reviews, only: [:create]
  resources :deposites, only: [:create,:show]
  namespace :tenant do 
    resources :tenants do
      collection do 
        get :payments
        get :dashboard
        get :myhouse
      end
      resources :tenant_profile, path: :profile
        
    end
  end
  resources :charges 
  get 'charges/booking'
  namespace :owner do
    resources :house_owners do
     collection do 
        get :my_houses
        get :dashboard
        get :my_payments
        get :my_credits
        get :my_notifications
      end
    resources :house_owner_profile
    resources :visit_schedules, only: [:index,:show]
  end
end 

end

app/models/booked_house.rb
class BookedHouse < ActiveRecord::Base
	belongs_to :house
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :tenant
	belongs_to :house
end

app/models/city.rb
class City < ActiveRecord::Base
	
end

app/models/deposite_rent.rb
class DepositeRent < ActiveRecord::Base
	belongs_to :house
	belongs_to :tenant
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :house_owner
	has_many :bookings
	has_many :deposite_rents
	has_many :room_rents
	has_many :tenants 
	has_many :visit_schedules
	has_many :booked_houses

	validates :house_image, :city, :location, :latitude, :longitude, presence: true
	
	mount_uploaders :house_image, ImageUploader
	
	acts_as_mappable :default_units => :kms,:lat_column_name => :latitude, :lng_column_name => :longitude

end

app/models/house_owner.rb
class HouseOwner < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  	has_one :house_owner_profile
  	has_many :houses
	has_many :visit_schedules
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/other_amenitie.rb
class OtherAmenitie < ActiveRecord::Base
end

app/models/owner_payment.rb
class OwnerPayment < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
	validates :name, :phone, :email, :room_for, :city, :location, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base 
end

app/models/room_rent.rb
class RoomRent < ActiveRecord::Base
	belongs_to :house
	belongs_to :tenant
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  has_one :tenant_profile
  has_many :bookings
  has_many :room_rents
  has_many :deposite_rents 
  belongs_to :house
  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/tenant_profile.rb
class TenantProfile < ActiveRecord::Base
	belongs_to :tenant
	def full_permamnent_address
		l = ''
		l << p_address if p_address && !p_address.blank?
    l << ' '
		l << p_city if p_city && !p_city.blank?
    l << ' '
		l << p_state if p_state && !p_state.blank?
  	end

  	#validates :DOB, :sex, :p_address, :p_city, :p_state, presence: true
  	mount_uploader :image, ImageUploader
  	mount_uploader :address_proof, ImageUploader
  	mount_uploader :identity_proof, ImageUploader
  	mount_uploader :cheque, ImageUploader
  	mount_uploader :employment_proof, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :first_name, :last_name, :contact_number, presence: true 
  # #mount_uploader :avatar, LogoUploader

  after_create :send_signup_mail
  
    def send_signup_mail
      UserMailer.signup_mail(self).deliver
    end


  # def should_be_house_owner_user?
  #   type == "HouseOwner"
  # end

  # def should_be_tenant_user?
  #   type == "Tenant"
  # end
 end

app/models/visit_schedule.rb
class VisitSchedule < ActiveRecord::Base
	belongs_to :house
	belongs_to :house_owner
	validates :name, :email, :phone, :date, :time, presence: true
end

app/controllers/tenant/tenant_profile_controller.rb
class Tenant::TenantProfileController < ApplicationController
	before_filter :authenticate_tenant!
  def edit
  	@user = current_tenant
     @city  = City.all
      @state  = State.all
    @tenant_profile = current_tenant.tenant_profile
  end
  def update
    @user = current_tenant
    @city  = City.all
     @state  = State.all
     @tenant_profile = TenantProfile.find(params[:id])
    if @tenant_profile.update_attributes(profile_params)
      redirect_to :back, notice: 'Profile updated successfully.'
    else
      render 'edit'
    end
  end
  def show

    @tenant = current_user
    @tenant_profile = current_user.tenant_profile
   
  end
    

  private
  def profile_params
   params.require(:tenant_profile).permit(:first_name,:last_name,:email,:contact_no,:image,:DOB,:sex,
    :identity_proof,:address_proof,
    :p_address,:p_city,:p_state,:p_pincode,
    :occupation,:orgnization,:office_email,:years_of_employement,:employment_proof,
    :account_holder,:account_number,:bank_name,:ifsc_code,:cheque,:bank_name,
    :emergency_person_name,:emergency_person_contact,:emergency_person_relationship,:emergency_person_address
    )
  end
end

app/controllers/tenant/tenants_controller.rb
class Tenant::TenantsController < ApplicationController
	before_filter :authenticate_tenant!
  respond_to :html, :js

  def dashboard    
    @booking = BookedHouse.where(tenant_id: current_user.id).first
    unless @booking.blank?
      @house = House.find(@booking.house_id)
    end
    if current_user.tenant_profile.nil?
      @tenant_profile = TenantProfile.new(tenant_id: current_user.id)
      @tenant_profile.save(validate: false)
    else
      @tenant_profile = current_user.tenant_profile
    end
    
  end

  def show
    @tenant = current_user
     @tenant_profile = current_user.tenant_profile
  end
  
  def payments    
    @rent = RoomRent.where(tenant_id: current_user.id).all
    @dues = 0
    @rent.each do |rent|
      if rent.status == 'dues'
        @dues += rent.rent_amount 
      end
    end
    @myhouse = BookedHouse.where(tenant_id: current_user.id).first
    
  end
  
  def myhouse    
   @booking = BookedHouse.where(tenant_id: current_user.id).first 
    unless @booking.blank?
      @house = House.find(@booking.house_id)
      @deposite = @booking.rent
    end

  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
	before_filter :authenticate_tenant!
   respond_to :html, :js
  def dashboard
  	
    @tenant = current_user
    
    if current_user.tenant_profile.nil?
      @tenant_profile = TenantProfile.new(tenant_id: current_user.id)
      @tenant_profile.save(validate: false)
    else
      @tenant_profile = current_user.tenant_profile
    end
  end

  def show
    @tenant = current_user
     @tenant_profile = current_user.tenant_profile
  end
  
  def payments    
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenant/tenants/_myhouse.html.erb
<div class="tenat-house">
	<div align="center">
		<h3 class="uppercase">My House</h3>
	</div>
	<div class="row">
		<% unless @booking.blank? %>
		<div class="col-sm-4">
			<%=image_tag @house.house_image.first.url(:thumb), class:"img-responsive"%>
		</div>	
		<div class="col-sm-8">
			<h5><%= @house.name %></h5>
			<h5><%= @house.location %></h5>
			<% my_deposite = DepositeRent.where(tenant_id: current_user.id, house_id: @booking.house_id).first %>
			<% if my_deposite.blank? %>
			<div class="alert alert-warning">
				<h5>you have not pay your deposite please pay now.</h5>
				<%= form_tag deposites_path do %>
						<%= hidden_field_tag 'house_id',nil, value: @booking.house_id %>
						<%= hidden_field_tag 'deposite',nil, value: @booking.rent.to_f*2 %>
						<%= hidden_field_tag 'tenant',nil, value: current_user.id%>
						<%= hidden_field_tag 'bed_room',nil, value: @booking.bed_room_id %>
						
						<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
						  	data-key="<%= Rails.configuration.stripe[:publishable_key] 	%>"
						  	data-description="Pay Token money/first month rent" data-label = 'Pay Now'
						  	data-amount="<% @booking.rent.to_f %>"
						  	data-locale="auto">
					  	</script>	
					<% end %>
				
			</div>
			<% end %>
		</div>
		<% else %>
		<div align="center">
			<h5>You have'nt book any house.</h5>
			<%= link_to "Explore houses", search_index_path(city: "Indore"),class:"btn btn-lg"%>
		</div>
		<% end %>

	</div>
</div>
<hr style="width:100%; border:1px solid #ccc;">
<% unless @booking.blank? %>
<div class='pt20'>
	<div class="row leave_review">
			<h5 class="text-center uppercase"> Tell others about this house - write a review </h5>
			<div class="col-sm-6 col-sm-offset-3">
				<%= form_for Review.new do |f|  %>
				<div>
					<%= f.text_area :message,rows:"3", placeholder:"Write a review", style: "border: 1px solid #c4c4c4;"%>
				</div>
				<%= f.hidden_field :tenant_id, value: current_user.id%>
				<%= f.hidden_field :house_id, value: @house.id%>
				<div>
					<%= f.submit 'review', class: 'btn btn-sm'%>
				</div>
				<% end %>
			</div>
	</div>
</div>
<% end %>

app/views/tenant/tenants/_payments.html.erb
<div class="tenat-payment">
	<div align="center">
		<h3 class="uppercase">My Payments</h3>
	</div>
	<div align="center">
		<a href="" class="btn">Unpaid Dues</a>
		<a href="" class="btn">Already Paid</a>
	</div>
	<div>
		<table class="table table-responsive">
			<tr>
				<td>Month</td>
				<td>Date</td>
				<td>Amount</td>
				<td>Status</td>
				<td>Reciept</td>
			</tr>
			<% @rent.each do |rent| %>
			<tr>
				<td><%= rent.month %></td>
				<td><%= rent.rent_date %></td>
				<td><%= rent.rent_amount%></td>
				<td><%= rent.status%></td>
				<% if rent.status == 'paid' %>
					<td><a href="">Get Reciept</a></td>
				<% elsif rent.status == 'dues' %>
					<td>
					<%= form_tag room_rents_path do %>
						<%= hidden_field_tag 'id',nil, value: rent.id %>
						<%= hidden_field_tag 'house_id',nil, value: rent.house_id %>
						<%= hidden_field_tag 'rent',nil, value: rent.rent_amount.to_f%>
						<%= hidden_field_tag 'month',nil, value: rent.month %>
						<%= hidden_field_tag 'tenant',nil, value: current_user.id%>
						<%= hidden_field_tag 'bed_room',nil, value: @myhouse.bed_room_id %>
						
						<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
						  	data-key="<%= Rails.configuration.stripe[:publishable_key] 	%>"
						  	data-description="Pay room rent" data-label = 'Pay Now'
						  	data-amount="<% rent.rent_amount.to_f%>"
						  	data-locale="auto">
					  	</script>	
					<% end %>
					</td>
				<% end %> 
			</tr>
			<% end %>
		</table>
		<h4>Total Amount to Pay: ₹ <span><%= @dues %></span></h4>

	</div>
</div>
<style type="text/css">
.stripe-button-el{
	padding: 0px !important;
	width:auto !important;
	text-transform: none !important;
	letter-spacing: 0px !important;
	height: 30px !important;
	border: none !important;
}
</style>

app/views/tenant/tenants/_wishlists.html.erb
<div class="tenat-wishlist">
	<div align="center">
		<h3 class="uppercase">MY WISHLIST</h3>
	</div>
	<div>
		<h4>Currently No House in the Wishlist!!!!</h4>
	</div>
</div>

app/views/tenant/tenants/dashboard.html.erb
<section class="custom-section">
	<div class="container">
		<div class="dashboard-header">
			<div class="row">
				<div class="col-sm-3">
					<%=image_tag @tenant_profile.image.url, class:"img-responsive",height:'100',width:'120'%>
				</div>
				<div class="col-sm-9">
					<h3>STILL PAYING YOUR RENT?</h3>
					<p> Share your Referral Code <span style="color:#47b475;">CWWIYG </span> with your friends. If your friend uses your referral code while booking, you get 7 days of stay absolutely FREE! And your friend gets 7 days.
						If you help us fill the last bed in your house, you get a flat Rs 5,000 OFF your next month’s rent. 
					</p>
				</div>
			</div>
		</div>	

		</br>
		<hr>
		<div class="row">
			<div class="col-sm-3 sidebar-left-custom">
				<div class="widget text-center">
					<!-- <h6 class="title"></h6>
					<hr> -->
					<ul class="link-list uppercase">
						<li>
							<div class="li-dashboard"><%= link_to "My house",  myhouse_tenant_tenants_path, remote: "true"%>
							</div>
						</li>						
						<li>
							<li> 
								<div class="li-dashboard"><%= link_to "My Payments",  payments_tenant_tenants_path, remote: "true"%></div> 							
							</li>
						</li>
						<li>
							<div class="li-dashboard"><span>My wishlists</span></div>
						</li>
						<li>
							<div class="li-dashboard "><span>My credits</span></div>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-sm-9" id="tenant-dashboard-section" style="border-left: 1px solid #ccc;">
				<%= render 'myhouse'%>
			</div>
		</div>
	</div>
</section>

app/views/tenant/tenants/myhouse.js.erb
$('#tenant-dashboard-section').html("<%= j (render 'myhouse') %>");
$('#tenant-dashboard-section').slideDown(350);

app/views/tenant/tenants/payments.js.erb
$('#tenant-dashboard-section').html("<%= j (render 'payments') %>");
$('#tenant-dashboard-section').slideDown(350);

app/views/tenant/tenants/show.html.erb
<% if !current_user.tenant_profile.valid? %>
<p class="alert alert-warning">
	Your profile is incomplete. Please fill out more of your

	<%= link_to 'Update Profile',  edit_tenant_tenant_tenant_profile_path(tenant_id: current_user.id, id: current_user.tenant_profile.id)%>
</p>
<%end%>

<section>
	<div class="row">
	<div class="container-fluid">
		<div class="col-sm-4 ">
			<div class=" pt-1 text-center">
				<h5 class="uppercase"></h5>
				<%= image_tag @tenant_profile.image_url(:thumb) if @tenant_profile.image? %>

			</div>
			<!--end of pricing table-->
		</div>
		<div class="col-sm-4 t-profile-info">
			<div class=" pt-1  boxed">
				<h5 class="uppercase">Personal info</h5>
				<p>name: <span><%=@tenant.full_name%></span> </p>
				<p>Gender: <span>
					<%="Male" if @tenant_profile.sex == "true" %>
					<%="Female" if @tenant_profile.sex == "false"  %>
					</span> 
				</p>
				<p>Birth date: <span><%=@tenant_profile.DOB%></span> </p>
				<p>email:<span><%=@tenant.email%></p>
				<p>About me: <span><%=@tenant_profile.bio%></span> </p>

			</div>
			<!--end of pricing table-->
		</div>
		<div class="col-sm-4 t-profile-info">
			<div class="pt-1 ">
				<h5 class="uppercase">Address</h5>
				<p>Permanent Address:<span><%=@tenant_profile.full_permamnent_address%></span></p>
				<p>Contact Number:<span><%=@tenant.contact_number%></span></p>

				
			</div>
			<!--end of pricing table-->

		</div>
			
		</div>
	</div>
	<div class="container">
			<%= link_to 'Update Profile',  edit_tenant_tenant_tenant_profile_path(tenant_id: current_user.id, id: current_user.tenant_profile.id), class:'btn'%>
			<%= link_to 'Update Account', edit_tenant_registration_path, class:'btn'%>
		</div>
			
</section>