config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'requirements/new'
  get 'requirements/create'
  get 'tenant/tenant_profile/edit'
  get 'house_owner_profile/edit'
  get 'owner/house_owners/dashboard'
  get 'tenant/tenants/dashboard'
  get 'tenant/tenants/profile'
  get 'home/index'
  get 'home/owner'
  get 'home/tenant'
  get 'home/ghomeshouses'
  get 'home/error'
  get 'payments/bed_confirmation'
  post 'payments/confirmation'
  get 'payments/booking'
  devise_for :tenants, skip: [:sessions]
  devise_for :house_owners, skip: [:sessions]
  devise_for :users, skip: :registrations

   root 'home#index'
  resources :search, only: [:new, :index]
  resources :requirements , only: [:create]
  resources :houses, except: [:index,:destroy]
  resources :visit_schedules, only: [:new,:create,:edit, :show]
  resources :payments
  resources :room_rents, only:[:new,:create, :show]
  resources :reviews, only: [:create]
  resources :deposites, only: [:create,:show]
  namespace :tenant do 
    resources :tenants do
      collection do 
        get :payments
        get :dashboard
        get :myhouse
      end
      resources :tenant_profile, path: :profile
        
    end
  end
  resources :charges 
  get 'charges/booking'
  namespace :owner do
    resources :house_owners do
     collection do 
        get :my_houses
        get :dashboard
        get :my_payments
        get :my_credits
        get :my_notifications
      end
    resources :house_owner_profile
    resources :visit_schedules, only: [:index,:show]
  end
end 

end

app/models/booked_house.rb
class BookedHouse < ActiveRecord::Base
	belongs_to :house
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :tenant
	belongs_to :house
end

app/models/city.rb
class City < ActiveRecord::Base
	
end

app/models/deposite_rent.rb
class DepositeRent < ActiveRecord::Base
	belongs_to :house
	belongs_to :tenant
end

app/models/house.rb
class House < ActiveRecord::Base
	belongs_to :house_owner
	has_many :bookings
	has_many :deposite_rents
	has_many :room_rents
	has_many :tenants 
	has_many :visit_schedules
	has_many :booked_houses

	validates :house_image, :city, :location, :latitude, :longitude, presence: true
	
	mount_uploaders :house_image, ImageUploader
	
	acts_as_mappable :default_units => :kms,:lat_column_name => :latitude, :lng_column_name => :longitude

end

app/models/house_owner.rb
class HouseOwner < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  	has_one :house_owner_profile
  	has_many :houses
	has_many :visit_schedules
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/other_amenitie.rb
class OtherAmenitie < ActiveRecord::Base
end

app/models/owner_payment.rb
class OwnerPayment < ActiveRecord::Base
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
	validates :name, :phone, :email, :room_for, :city, :location, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base 
end

app/models/room_rent.rb
class RoomRent < ActiveRecord::Base
	belongs_to :house
	belongs_to :tenant
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  has_one :tenant_profile
  has_many :bookings
  has_many :room_rents
  has_many :deposite_rents 
  belongs_to :house
  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/tenant_profile.rb
class TenantProfile < ActiveRecord::Base
	belongs_to :tenant
	def full_permamnent_address
		l = ''
		l << p_address if p_address && !p_address.blank?
    l << ' '
		l << p_city if p_city && !p_city.blank?
    l << ' '
		l << p_state if p_state && !p_state.blank?
  	end

  	#validates :DOB, :sex, :p_address, :p_city, :p_state, presence: true
  	mount_uploader :image, ImageUploader
  	mount_uploader :address_proof, ImageUploader
  	mount_uploader :identity_proof, ImageUploader
  	mount_uploader :cheque, ImageUploader
  	mount_uploader :employment_proof, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :first_name, :last_name, :contact_number, presence: true 
  # #mount_uploader :avatar, LogoUploader

  after_create :send_signup_mail
  
    def send_signup_mail
      UserMailer.signup_mail(self).deliver
    end


  # def should_be_house_owner_user?
  #   type == "HouseOwner"
  # end

  # def should_be_tenant_user?
  #   type == "Tenant"
  # end
 end

app/models/visit_schedule.rb
class VisitSchedule < ActiveRecord::Base
	belongs_to :house
	belongs_to :house_owner
	validates :name, :email, :phone, :date, :time, presence: true
end

app/controllers/house_owners_controller.rb
class HouseOwnersController < ApplicationController
	before_filter :authenticate_house_owner!
  def dashboard
  	if current_user.house_owner_profile.nil?
      @house_owner_profile = HouseOwnerProfile.new(house_owner_id: current_user.id)
      @house_owner_profile.save(validate: false)
    #   @house_owner = current_user
    # @houses = House.all.where(house_owner_id: current_user.id)

    else
      @house_owner_profile = current_user.house_owner_profile
      @house_owner = current_user
    @houses = House.all.where(house_owner_id: current_user.id)
    end
  end
  def show
  	@house_owner = current_user
     @house_owner_profile = current_user.house_owner_profile
  end
  def my_houses
    @house_owner = current_user
    @houses = House.all.where(house_owner_id: current_user.id)

  end
  def my_payments
  end
  
end

app/controllers/owner/house_owners_controller.rb
class Owner::HouseOwnersController < ApplicationController
	before_filter :authenticate_house_owner!, except: [:show]
  def dashboard
  	if current_user.house_owner_profile.nil?
      @house_owner_profile = HouseOwnerProfile.new(house_owner_id: current_user.id)
      @house_owner_profile.save(validate: false)
    #   @house_owner = current_user
    # @houses = House.all.where(house_owner_id: current_user.id)

    else
      @house_owner_profile = current_user.house_owner_profile
      @house_owner = current_user
    @houses = House.all.where(house_owner_id: current_user.id)
    end
  end
  def show
  	@house_owner = current_user
     @house_owner_profile = current_user.house_owner_profile
  end
  def my_houses
    @house_owner = current_user
    @houses = House.all.where(house_owner_id: current_user.id)

  end
  def my_payments
    @payments = OwnerPayment.where(house_owner_id: current_user.id)
  end
  def my_credits
  end
  def my_notifications
    @house_owner = current_user
    @visit_schedules = VisitSchedule.where(house_owner_id: current_user.id)
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/house_owners_helper.rb
module HouseOwnersHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/house_owners/_my_houses.html.erb
<section class="pt0 ">
  <div class="owner-my-house">
    <h3 class="uppercase">My Houses</h3>
  <table class="table">
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @houses.each do |house| %>
      <tr>
        <td><%= house.id %></td>
        <td><%= house.location %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Register another house', new_house_path, class:'btn' %>
  </div>
</section>

app/views/house_owners/dashboard.html.erb
<section class="custom-section">
	<div class="container">
		<div class="dashboard-header">
			<div class="row">
				<div class="col-sm-3">
					<%=image_tag @house_owner_profile.image.url, class:"img-responsive",height:'200',width:'100%'%>
				</div>
				<div class="col-sm-9">
					<h3>Register Your House with GoogleHomes</h3>
					<p> Share your Referral Code <span style="color:#47b475;">CWWIYG </span> with your friends. If your friend uses your referral code while registring, you get Rs5000! And your friend gets 4000.
					</p>
				</div>
			</div>
		</div>	

		</br>
		<div class="row">
			<div class="col-sm-3 sidebar-left-custom">
				<div class="widget">
					<h6 class="title">Blog Categories</h6>
					<hr>
					<ul class="link-list uppercase">
						<li>
							<div class="li-dashboard"><a href="/house_owners/my_houses" data-remote ="true">My House</a></div>
						</li>						
						<li>
							
						</li>
						<li>
							<div class="li-dashboard"><a href="/house_owners/my_payments" data-remote ="true">My payments</a></div>
						</li>
						<li>
							<div class="li-dashboard "><span>My credits</span></div>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-sm-9" id="owner-dashboard-section">
				<%#= render my_houses'%>
			</div>
		</div>		
	</div>	
</div>
</section>

app/views/house_owners/show.html.erb
<div class="container-fluid">
	

	<h1>House owner profile</h1>
	<%= link_to 'Update Profile',  edit_house_owner_house_owner_profile_path(house_owner_id: current_user.id)%>
	<%# if !current_user.tenant_profile.valid? %>
	<p class="alert alert-warning">
		Your profile is incomplete. Please fill out more of your

		<%= link_to 'Update Profile',   edit_house_owner_house_owner_profile_path(house_owner_id: current_user.id, id: current_user.house_owner_profile.id)%>
	</p>
</div>
<%#end%>
<section class="custom-section">
	<div class="container">
		<h3>House owner#profile</h3>
		<div class="col-sm-6">
			<p>name: <%=@house_owner.full_name%> </p>
			<p>Profile image</p>
			<%= image_tag @house_owner_profile.image_url(:thumb) if @house_owner_profile.image? %>
			<p>Gender: <%=@house_owner_profile.sex%> </p>
			<p>Bio: <%=@house_owner_profile.bio%> </p>
			<p>DOB: <%=@house_owner_profile.DOB%> </p>
			<p>email:<%=@house_owner.email%></p>
			<p>Occupation: <%=@house_owner_profile.occupation%> </p>
			<p>Working Details: <%=@house_owner_profile.work_detail%> </p>
			<p>contact_number:<%=@house_owner.contact_number%></p>
			<p>Permanent Address:<%=@house_owner_profile.full_permamnent_address%></p>
			<p>Permanent Address:<%= @house_owner_profile.full_corespondence_address%></p>
			<p>contact_number:<%=@house_owner.contact_number%></p>
		</div>
		<div class="col-sm-6">
			<%= link_to 'Update Profile',  edit_house_owner_house_owner_profile_path(house_owner_id: current_user.id, id: current_user.house_owner_profile.id)%>
		</div>
	</div>	
</section>